services:
  bozo-ai-langchain-wiki:
    build: bozo-ai-langchain-wiki
    restart: always
    environment:
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_COMPLETION_DEPLOYMENT_NAME: ${AZURE_OPENAI_COMPLETION_DEPLOYMENT_NAME}
      AZURE_OPENAI_CHAT_DEPLOYMENT_NAME: ${AZURE_OPENAI_CHAT_DEPLOYMENT_NAME}
      AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME: ${AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME}
      LANGCHAIN_TRACING_V2: ${LANGCHAIN_TRACING_V2}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      PORT: 3000
  bozo-ai-discord-qna:
    build: bozo-ai-discord-qna
    restart: always
    environment:
      DiscordToken: ${DiscordToken}
      AskWikiURL: "http://bozo-ai-langchain-wiki:3000/agent/invoke"
      DevIds__0: ${DevIds__0}
      DevIds__1: ${DevIds__1}

